travis:
  secure:
    BINSTAR_TOKEN: Ab5IFEPGOKBOuhdvPJMlJX1dGFomBGhw0P1Vjv2ylPRl8aU6GXMCz75ceAzov+mHD6D/1B4Yl6IWVx/ZEEE6T5MwFmGURW8/s7gsoFW1dGhN2btlwApOuRPLP29LwaA7cyySAFA/CiPByi8MMgwWgvLC1DwEvQS/n49bNa++1YLm7s3HgtMmOiEBmh/pCfwmlwZxLon6stcrRizkeM2qc8cHp4sYKWGWpPDjCthgbOPW9vGlheMsTtxI0yLIgVJ19Glc1SecyEosQsbRnroEeWG565EREQ1jBc/qunC/ipQBNOySfZUFwfsdzYlyKTClVLvg1vOjihWVRqRxT10JxD5VVca6hD8P3GwZxSdsL0genPZBqP+P8CEY+er3+IHhNwgqNvzcACsf5clU4pwdyZEnN5k/96S/qqhWkXMieVpuLwevVBwhV8DAOexzDjZfuwHTCBWqEczSK8JajoWTdtShm9OklEZV7y6+weNqPlaiBHwjcO+4i1o6gHDlIvV/SKpHtXZZ0Xjt7Qs9I5kzaOUkfhSQqBptzu/YA4hGV3O4zDEvw0Q3/g7xmZDEfx360TCsc7RDoLGfzk3jeCYq4oJSVj9dEVeFx0Sqj7egYzt1OMKhDuKMlblMi6Mys3MGIpAXnmofqpfzl4BkB9qolAzf+tn2Vmuimro1MNuwKDc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
