travis:
  secure:
    BINSTAR_TOKEN: f8D4gNJDtORGVNmCYWn5mwTkvFqO8VSxrWu5tFUwCgXXFHmKhhg417VJ4M7sWa0cBf2P9TQkr4Y29ZRxeLhaXfJi8Y11D85U/VdDOQ87nTmCagwHrzzPKqdNIWQ1dpMDozyfmDh3YOaWq4gZm2UETFALp/1dnA1/z+P/b4m1s9Dd86QDbzcVa7N2uVLD9V8npGGn/CpEeCMyXDsl96Si2lcDQVV1Ad9g5DPiv1H++W14yQjqqGbh1HVqhWBW8Xo63f8pDOh8PkWs5MlnedPBnolrXS7mBbvzE+bJ2IEbZols4JreNmQgyPbX/9oWDw+/PYrYadNB6ISMyrZndzId9CvfnlGKHrb3S9IYZPOcJlekI/fu+PYRyDHQ1VV2FMWbXAEaOkSNZ3syg5GONwGx1Fa+OrIlp5xIK2sXQMYTuj4EpFLA+U25BG6GefpTJE/LXQEHnQwdyhd4kJjIMCDJI3G7g4kKvL1mSC8/uWkWV73nyLp9+LjyfK7MMjF7lbLvL+bcqEqfj153OewhxReEE03l/DmNDitZYUuY99lMPVyq8ucP16e920yIO9Mf21E9ogFJ5+ycvEeXXCDM8dwWV2PxVzVkSbZb7IbiAARJkkfX0UcYgjSklEccQK6CgwLWoXUuzX7ZopFLhY9o/RYsoXTqGujpoOmaH0wh721hvQA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
